site_name: ESG Center 技术文档
repo_url: 
repo_name: ESG Center Documentation

theme:
  name: material
  language: zh
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - primary: white
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav: 
  - 首页: index.md
  - 组件: 
    - 网络爬虫: crawler.md
    - 网络应用: app.md
  - 关于:
    - 项目简介: intro.md
    - 团队: team.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences